import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.scss';

const lackLine = localFont({
  src: './styles/fonts/Lack-Regular.woff2',
});

const montserrat = localFont({
  src: './styles/fonts/MontserratAlternates-Regular.woff2',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lackLine.className} ${montserrat.className}`}>{children}</body>
    </html>
  );
}
